version: '3'

services:
  web:
      build: .
      ports:
        - 3030:8080
      volumes:
        - ${IDEA}:${IDEA}
        - ${JREBEL}:/jrebel
        - ${REBEL_BASE}:/rebelbase
        - ${XREBEL}:/xrebel
      depends_on:
        - db

  db:
    image: postgres:10-alpine
    ports:
      - 2345:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  webapps:
  pgdata: